Repository COS301-SE-2022/Slip-Snapper, pull requests merged in 2022-08, with the labels that each got.

#289 🎨 (feature/api) Added basic error handling to all db queries
  backend/api/apps/src/db.js
Labels: type:enhancement, priority:low, scope:db, scope:api

#290 ✨ Database queries, descriptive statistics - average spent without time frame
  backend/api/apps/src/db.js
Labels: priority:low, scope:db, type:feature, scope:feature

#295 Feature/api: Added JWT to routes
  backend/api/apps/server.js
  backend/api/apps/src/S3Bucket.js
  backend/api/apps/src/db.js
  backend/api/apps/src/index.js
  backend/api/apps/src/routes/auth.js
  backend/api/apps/src/routes/item.js
  backend/api/apps/src/routes/ocr.js
  backend/api/apps/src/routes/report.js
  backend/api/apps/src/routes/slips.js
  backend/api/apps/src/token.js
  backend/api/apps/tests/routes/auth.test.js
  backend/api/apps/tests/routes/items.test.js
  backend/api/apps/tests/routes/ocr.test.js
  backend/api/apps/tests/routes/report.test.js
  backend/api/package.json
  backend/api/yarn.lock
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
Labels: priority:low, scope:api, type:change

#296 🚧 Database structure
  backend/api/prisma/migrations/20220814045532_only_date/migration.sql
  backend/api/prisma/schema.prisma
Labels: type:enhancement, priority:high, scope:db

#297 🚧 (database structure) report and slip numbers added
  backend/api/prisma/migrations/20220814074638_json_budget/migration.sql
  backend/api/prisma/migrations/20220814103239_relationalmodel/migration.sql
  backend/api/prisma/migrations/20220814110212_budgetsjson/migration.sql
  backend/api/prisma/schema.prisma
Labels: priority:high, scope:db, type:change

#299 💄 (ui) Small fixes to Login/Register pages UI
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/app/theme/login-register.css
  frontend/apps/slip-snapper/src/app/theme/register.css
Labels: type:enhancement, priority:low, scope:ui

#304 🚧 (ui): Fixing budget rendering issue
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
Labels: type:enhancement, priority:low, scope:ui

#305 🚧 (db queries) addUser and getUser updated
  backend/api/apps/src/db.js
  backend/api/prisma/migrations/20220818175310_db_json/migration.sql
  backend/api/prisma/migrations/20220818215048_add_report_total/migration.sql
  backend/api/prisma/schema.prisma
Labels: type:enhancement, priority:high, scope:db, type:change

#306 🚧 (db queries) expanded the budget json object to include states
  backend/api/apps/src/db.js
Labels: priority:high, scope:db, type:feature, scope:feature

#307 ♻️ (ui) : Fixed/Refactored budgets on Profile Page
  frontend/apps/slip-snapper/src/app/components/Budget.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
Labels: type:enhancement, priority:medium, scope:ui

#308 🎨 (feature/api): Added delete slip api call
  backend/api/apps/src/routes/assets/maskable_icon.png
  backend/api/apps/src/routes/item.js
  backend/api/apps/src/routes/report.js
  frontend/apps/slip-snapper/src/api/apiCall.js
Labels: priority:low, scope:api, type:change

#310 🚧 (db queries) update weekly and monthly category budgets
  backend/api/apps/src/db.js
Labels: priority:high, scope:db, type:feature, scope:feature

#311 ♻️ (ui): Refactor AddEntry UI
  frontend/apps/slip-snapper-e2e/src/integration/home-integration.spec.ts
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/theme/addEntry.css
  frontend/package.json
  frontend/yarn.lock
Labels: type:enhancement, priority:high, scope:ui, type:change, type:test

#312 🎨 (db query) changed budgets to nested json object
  backend/api/apps/src/db.js
Labels: type:enhancement, priority:high, scope:db, type:feature

#313 ♻️ (ui): Refactor EditReceipt UI
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
Labels: type:enhancement, priority:high, scope:ui, type:change, type:test

#314 ✨ (db query) get category budget created
  backend/api/apps/src/db.js
Labels: priority:high, scope:db, type:feature

#315 🐛 (db queries) get general user query updated
  backend/api/apps/src/db.js
Labels: priority:high, scope:db, type:bug

#316 ♻️ (ui): Refactor EditSlip UI
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
  frontend/apps/slip-snapper/src/app/theme/addEntry.css
  frontend/apps/slip-snapper/src/app/theme/editSlip.css
Labels: type:enhancement, priority:medium, scope:ui, type:change

#317 🚧 (db query) get item method updated to fit the new db structure
  backend/api/apps/src/db.js
Labels: priority:high, scope:db, type:change

#318 :construction: (db queries) updated retrieve All slips method
  backend/api/apps/src/db.js
Labels: priority:high, scope:db, type:change

#319 🚧 (db) bug fixes, queries working with frontend and api
  backend/api/apps/src/db.js
  backend/api/prisma/migrations/20220821110026_implicit_relations/migration.sql
  backend/api/prisma/migrations/20220821131228_onetoone_data/migration.sql
  backend/api/prisma/migrations/20220821132728_manytomanydata/migration.sql
  backend/api/prisma/schema.prisma
Labels: priority:high, scope:db, type:bug

#320 ♻️ (ocr) migrating ocr + performance increase
  backend/api/apps/src/S3Bucket.js
  backend/api/apps/src/index.js
  backend/api/apps/src/routes/ocr.js
  backend/api/apps/src/routes/report.js
  backend/api/apps/tests/routes/assets/IMG_5593.jpg
  backend/api/apps/tests/routes/ocr.test.js
  backend/api/package.json
  backend/api/yarn.lock
  frontend/apps/slip-snapper-e2e/src/fixtures/Login.json
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/components/usePhotoGallery.js
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
Labels: type:enhancement, priority:high, type:change, scope:feature

#323 💄 (ui): Implemented Budget States
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/report.js
  frontend/apps/slip-snapper/src/app/components/Budget.tsx
  frontend/apps/slip-snapper/src/app/components/EditBudgets.tsx
  frontend/apps/slip-snapper/src/app/theme/profile.css
Labels: type:enhancement, priority:low, scope:ui

#324 💄 (ui): Updated Login UI
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/theme/login-register.css
Labels: priority:low, scope:ui, type:change

#325 ♻️ (ui): Added date picker and updated date format
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
Labels: type:enhancement, priority:medium, scope:ui, type:change

#326 💄 (ui): Implemented dynamic progress bars
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/components/Budget.tsx
  frontend/apps/slip-snapper/src/app/components/EditBudgets.tsx
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
Labels: type:enhancement, priority:medium, scope:ui

#327 ♻️ (ui): Category dropdown
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
  frontend/apps/slip-snapper/src/app/theme/addEntry.css
Labels: priority:medium, scope:ui, type:change

#328 🐛 (ui) Fixed bug in category budgets
  frontend/apps/slip-snapper/src/app/components/Budget.tsx
  frontend/apps/slip-snapper/src/app/components/EditBudgets.tsx
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
Labels: type:enhancement, priority:low, scope:ui

#329 🐛 various bug fixes
  frontend/apps/slip-snapper/src/app/components/Menu.tsx
  frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
  frontend/apps/slip-snapper/src/app/components/SlipItems.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/apps/slip-snapper/src/app/theme/FetchData.css
  frontend/apps/slip-snapper/src/app/theme/reportItem.css
  frontend/apps/slip-snapper/src/app/theme/viewReports.css
Labels: priority:high, type:bug, type:change, scope:feature

#330 :bug: (db query) fixed add and update slips query
  backend/api/apps/src/db.js
Labels: priority:high, scope:db, type:bug

#332 ♻️ (ui): Hide repetitive labels on desktop view
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
  frontend/apps/slip-snapper/src/app/theme/addEntry.css
Labels: priority:medium, scope:ui, type:change

#336 ♻️ (ui): Update UI of deleting of items
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
Labels: priority:low, scope:ui, type:change

#337 💄 (ui): Register page navigation
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
Labels: priority:low, scope:ui, type:change

#338 🐛 (ui): Fixed bugs on the EditReceipt page
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/item.js
  frontend/apps/slip-snapper/src/app/components/SlipItems.tsx
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
Labels: priority:low, scope:ui, type:bug

#339 🚧 (ui): Updated User Details section
  frontend/apps/slip-snapper/src/app/components/ProfileImage.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/theme/profile.css
Labels: priority:low, scope:ui, type:change

#340 🐛 (db query) fixed update slip
  backend/api/apps/src/db.js
Labels: priority:high, scope:db, type:bug

#342 :sparkles: (db query) delete slip query
  backend/api/apps/src/db.js
Labels: priority:high, scope:db, type:feature, scope:feature

#343 🚧 (ui): Experimental refactor of Receipts page
  frontend/apps/slip-snapper/src/app/components/SlipItems.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/apps/slip-snapper/src/app/theme/FetchData.css
  frontend/apps/slip-snapper/src/app/theme/SlipItems.css
Labels: priority:low, scope:ui, type:change

#345 ✨ (feature): Implement delete slip feature
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/item.js
  frontend/apps/slip-snapper/src/app/components/Budget.tsx
  frontend/apps/slip-snapper/src/app/components/EditBudgets.tsx
  frontend/apps/slip-snapper/src/app/components/SlipItems.tsx
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
  frontend/apps/slip-snapper/src/app/theme/profile.css
Labels: type:enhancement, priority:low, scope:ui

#347 🚧 (db query) fixed profiles page
  backend/api/apps/src/db.js
Labels: priority:high, scope:db, type:bug, type:feature

#350 🚧 (db structure) added emails and converted dates to str…
  backend/api/prisma/migrations/20220830120541_email_and_string_date/migration.sql
  backend/api/prisma/schema.prisma
Labels: priority:high, scope:db, type:change

#351 💄 (ui): Dynamic Budget time period icons
  frontend/apps/slip-snapper/src/app/components/Budget.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/theme/variables.css
Labels: priority:low, scope:ui, type:change

#352 🚧 (db queries) queries adjusted for string dates
  backend/api/apps/src/db.js
Labels: priority:high, scope:db, type:bug, type:change

#353 ✨ (db queries) extended category json
  backend/api/apps/src/db.js
Labels: priority:high, scope:db, type:feature, scope:feature

#354 🚧 (ui): Implemented UI for new category budgets. Minor bug fixes
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/item.js
  backend/api/apps/src/routes/report.js
  frontend/apps/slip-snapper/src/app/components/Budget.tsx
  frontend/apps/slip-snapper/src/app/components/EditBudgets.tsx
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
Labels: type:enhancement, priority:medium, scope:ui, type:bug

#355 💄 (ui): Added functionality to new categories
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/report.js
  frontend/apps/slip-snapper/src/app/components/Budget.tsx
  frontend/apps/slip-snapper/src/app/components/EditBudgets.tsx
Labels: type:enhancement, priority:low, scope:ui
