Repository COS301-SE-2022/Slip-Snapper, pull requests merged in 2022-07, with the labels that each got.

#187 :lipstick: (ui): Added component for budget editing
  frontend/apps/slip-snapper/src/app/components/EditBudgets.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
Labels: priority:low, scope:ui, type:feature

#188 💄(ui): Added components for Home page
  frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
Labels: type:enhancement, priority:low, scope:ui

#189 :bug: (ui): Fixed state permanence of budget checkboxes
  frontend/apps/slip-snapper/src/app/components/EditBudgets.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
Labels: priority:low, scope:ui, type:bug

#190 💄 (ui) : Added Component for Report Totals
  frontend/apps/slip-snapper/src/app/Tests/Home.spec.tsx
  frontend/apps/slip-snapper/src/app/Tests/__snapshots__/App.spec.tsx.snap
  frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
  frontend/apps/slip-snapper/src/app/components/ReportTotal.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
Labels: type:enhancement, priority:low, scope:ui

#191 ✅ (tests): Fixed Tests for the ReportTotals
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/Tests/Home.spec.tsx
  frontend/apps/slip-snapper/src/app/components/ReportTotal.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
Labels: priority:low, scope:ui, type:test

#192 💄 (ui): Updated CSS for Reports page
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/components/ViewReportItem.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/apps/slip-snapper/src/app/theme/viewReports.css
Labels: type:enhancement, priority:low, scope:ui

#194 💄 (ui): Added Component for User Stats
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/components/Budget.tsx
  frontend/apps/slip-snapper/src/app/components/EditBudgets.tsx
  frontend/apps/slip-snapper/src/app/components/UserStats.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
Labels: type:enhancement, priority:low, scope:ui

#195 (Feature/api): Added get report api skeleton
  backend/api/apps/src/db.js
  backend/api/apps/src/index.js
  backend/api/apps/src/routes/report.js
  backend/api/apps/tests/routes/auth.test.js
  backend/api/apps/tests/routes/items.test.js
  backend/api/apps/tests/routes/report.test.js
Labels: priority:low, scope:api, type:change, type:test

#197 💄 (ui) : Basic Functionality for AddEntry
  frontend/apps/slip-snapper/src/app/App.tsx
  frontend/apps/slip-snapper/src/app/components/TakePictureButton.tsx
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/theme/addEntry.css
  frontend/apps/slip-snapper/src/app/theme/home.css
Labels: priority:medium, scope:ui, type:feature

#198 💄 (ui): Added padding to dynamic budget items
  frontend/apps/slip-snapper/src/app/components/Budget.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/theme/profile.css
Labels: type:enhancement, priority:low, scope:ui

#199 💄 (ui): Updated new entry button
  frontend/apps/slip-snapper/src/app/Tests/__snapshots__/App.spec.tsx.snap
  frontend/apps/slip-snapper/src/app/components/Budget.tsx
  frontend/apps/slip-snapper/src/app/components/EditBudgets.tsx
  frontend/apps/slip-snapper/src/app/components/TakePictureButton.tsx
Labels: type:enhancement, priority:medium, scope:ui

#200 💄 (ui): Updated UI for the add entry page
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/theme/addEntry.css
Labels: type:enhancement, priority:low, scope:ui

#202 🚧 (parser): Expansion of text parser
  backend/api/apps/textProcessor/text_parser/parser.js
Labels: type:enhancement, priority:medium, scope:feature

#203 💄 (ui): Updated AddEntry page UI
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/theme/addEntry.css
Labels: type:enhancement, priority:low, scope:ui

#204 💄 (ui): Updated UI for EditSlip page
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
  frontend/apps/slip-snapper/src/app/theme/editSlip.css
Labels: type:enhancement, priority:low, scope:ui

#205 🚧 (parser): Expansion of parser
  backend/api/apps/textProcessor/text_parser/parser.js
Labels: type:enhancement, priority:medium, scope:feature

#207 ✨ (S3) : Set up a basic S3 file structure
  frontend/apps/slip-snapper/src/AWS/S3Bucket.ts
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/polyfills.ts
  frontend/package.json
  frontend/yarn.lock
Labels: priority:medium, type:feature, scope:feature

#208 ✨ (S3): added function to get objects from S3
  frontend/apps/slip-snapper/src/AWS/S3Bucket.ts
  frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
Labels: priority:low, type:feature, scope:feature

#210 Feature/db ✨ (db) changed database to include budgets model
  backend/api/prisma/migrations/20220717134658_new_budget_model/migration.sql
  backend/api/prisma/migrations/migration_lock.toml
  backend/api/prisma/schema.prisma
  backend/database/prisma/index.ts
  backend/database/prisma/prisma/migrations/20220714171931_new_budget_model/migration.sql
  backend/database/prisma/prisma/schema.prisma
Labels: priority:high, scope:db, type:change, scope:feature

#211 :construction: (S3): View pdfs
  frontend/apps/slip-snapper/src/AWS/S3Bucket.js
  frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
Labels: priority:medium, type:feature, scope:feature

#212 Feature/db ✨ (db) added reports model and migrations
  backend/api/prisma/migrations/20220717162027_new_reports_model/migration.sql
  backend/api/prisma/schema.prisma
  backend/database/prisma/prisma/migrations/20220717161149_new_report_model/migration.sql
  backend/database/prisma/prisma/schema.prisma
Labels: priority:high, scope:db, type:change, scope:feature

#213 🚧 (ui): Render Total for the Add Entry Page
  frontend/apps/slip-snapper/src/AWS/S3Bucket.js
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
Labels: type:enhancement, priority:low, scope:ui

#214 💄(ui): Added totals for AddEntry and EditSlip
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
Labels: type:enhancement, priority:low, scope:ui

#215 💄 (ui): Updated Recent Reports layout on Home Page
  frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
  frontend/apps/slip-snapper/src/app/theme/reportItem.css
Labels: type:enhancement, priority:low, scope:ui

#216 💄 (ui): Updated Home and Reports pages layout
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/Tests/Home.spec.tsx
  frontend/apps/slip-snapper/src/app/components/ReportTotal.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/apps/slip-snapper/src/app/theme/home.css
  frontend/apps/slip-snapper/src/app/theme/reportTotal.css
Labels: type:enhancement, priority:medium, scope:ui

#217 💄 (ui) : Added UI to view all reports
  backend/api/apps/src/routes/S3Bucket.js
  frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
  frontend/apps/slip-snapper/src/app/components/ViewReportItem.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: type:enhancement, priority:low, scope:ui

#218 (Feature/api) Updates to the api
  README.md
  backend/api/apps/src/routes/S3Bucket.js
  backend/api/apps/src/routes/report.js
  backend/api/apps/tests/routes/report.test.js
  backend/api/package.json
  backend/api/yarn.lock
  frontend/apps/slip-snapper/src/api/apiCall.js
Labels: type:enhancement, priority:low, scope:api

#219 :sparkles: (S3): Delete files from S3
  backend/api/apps/src/routes/S3Bucket.js
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: priority:medium, type:feature, scope:feature

#220 💄 (ui): Added functionality to view reports
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: type:enhancement, priority:low, scope:ui

#221 Feature/db ✨ (db queries) queries for the reports page
  backend/api/apps/src/db.js
  backend/database/prisma/index.ts
Labels: priority:high, scope:db, type:feature, scope:feature

#224 (Feature/api) Added api calls
  backend/api/apps/src/routes/S3Bucket.js
  backend/api/apps/src/routes/report.js
  frontend/apps/slip-snapper/src/api/apiCall.js
Labels: type:enhancement, priority:low, scope:api

#225 🚧 (S3): Upload report to bucket
  backend/api/apps/src/routes/S3Bucket.js
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: priority:medium, type:feature, scope:feature

#226 💄 (ui): updated buttons to call API
  frontend/apps/slip-snapper/src/app/components/ReportTotal.tsx
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: priority:medium, scope:ui, type:feature

#227 ✅ (Tests): Added Jest Tests for AddEntry Page
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
Labels: priority:low, scope:ui, type:test

#228 💄 (ui): Correctly Render contents
  frontend/apps/slip-snapper/src/app/components/UserStats.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: type:enhancement, priority:low, scope:ui

#230 🚧 Fixes, api call to fetch reports
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/S3Bucket.js
  backend/api/apps/src/routes/report.js
Labels: priority:medium, type:change, scope:feature

#231 💄 (ui): Updated UI to Render dynamically
  backend/api/apps/src/routes/report.js
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: type:enhancement, priority:low, scope:ui

#232 🚧 (api): Recent reports
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/S3Bucket.js
  backend/api/apps/src/routes/report.js
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: priority:medium, type:feature, scope:feature

#233 💄 (ui): Updated Home page to view Reports
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: type:enhancement, priority:low, scope:ui

#234 :sparkles: (api): Delete report from db
  backend/api/apps/src/routes/report.js
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: priority:medium, type:feature, scope:feature

#235 💄 (ui): Rendered Reports dynamically
  backend/api/apps/src/routes/report.js
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: type:enhancement, priority:low, scope:ui

#236 🚧 (refactor): Updated EditItem page UI
  frontend/apps/slip-snapper/src/app/components/FetchData.js
  frontend/apps/slip-snapper/src/app/pages/FetchData.css
Labels: priority:medium, type:change, scope:feature

#237 💄♻️ (ui, refactor): Refactored EditItem and minor UI fixes
  .vscode/settings.json
  frontend/apps/slip-snapper/src/app/App.tsx
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/Tests/Home.spec.tsx
  frontend/apps/slip-snapper/src/app/components/FetchData.js
  frontend/apps/slip-snapper/src/app/components/Menu.tsx
  frontend/apps/slip-snapper/src/app/components/NavButtons.tsx
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Receipts.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/apps/slip-snapper/src/app/theme/FetchData.css
  frontend/apps/slip-snapper/src/app/theme/addEntry.css
  frontend/apps/slip-snapper/src/app/theme/editSlip.css
Labels: type:enhancement, priority:low, scope:ui, type:change, scope:feature

#238 💄 (ui): Refactored EditSlip Page
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
  frontend/apps/slip-snapper/src/app/theme/addEntry.css
  frontend/apps/slip-snapper/src/app/theme/editSlip.css
Labels: type:enhancement, priority:low, scope:ui

#239 (Feature/api) frontend calls now use axios
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/report.js
  backend/api/apps/tests/routes/report.test.js
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/components/FetchData.js
  frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
  frontend/apps/slip-snapper/src/app/components/ReportTotal.tsx
  frontend/apps/slip-snapper/src/app/components/UserStats.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/package.json
  frontend/yarn.lock
Labels: priority:medium, scope:api, type:change

#240 :construction: (hosting): Heroku setup
  backend/api/Procfile
  backend/api/apps/server.js
Labels: priority:medium, type:feature, scope:feature

#241 🐛 (api): Updated headers in API calls
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/components/FetchData.js
  frontend/apps/slip-snapper/src/app/components/TakePictureButton.tsx
  frontend/apps/slip-snapper/src/app/components/usePhotoGallery.js
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
  frontend/apps/slip-snapper/src/app/pages/Receipts.tsx
Labels: priority:high, scope:api, type:bug

#242 ✨ (feature): Implemented sign up functionality
  backend/api/apps/src/routes/S3Bucket.js
  backend/api/apps/src/routes/auth.js
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/app/theme/home.css
Labels: priority:medium, type:feature, scope:feature

#243 ✨ (feature): Implemented Login functionality
  backend/api/apps/src/routes/auth.js
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/app/theme/login.css
Labels: priority:low, type:feature, scope:feature

#244 💄 (ui): Updated Profile Page UI
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/components/Budget.tsx
  frontend/apps/slip-snapper/src/app/components/EditBudgets.tsx
  frontend/apps/slip-snapper/src/app/components/UserStats.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/theme/profile.css
  frontend/apps/slip-snapper/src/app/theme/toasts.css
Labels: priority:medium, scope:ui, type:change

#245 ✅ (test): Added more Profile Page tests
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/Tests/__snapshots__/App.spec.tsx.snap
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
Labels: priority:low, scope:repository, type:test

#247 (Feature/api)
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/S3Bucket.js
  backend/api/apps/src/routes/report.js
  backend/api/apps/tests/routes/report.test.js
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
  frontend/apps/slip-snapper/src/app/components/ReportTotal.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: priority:low, scope:api, type:change

#248 ✅ (ui): Added more testing to Profile Page
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/Tests/__snapshots__/App.spec.tsx.snap
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
Labels: priority:low, scope:repository, type:test

#249 ✅ (test): Added tests to Profile Page
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
Labels: priority:low, scope:repository, type:test

#250 ✅ (testing) Cypress integration testing
  frontend/apps/slip-snapper-e2e/src/fixtures/InvalidLogin.json
  frontend/apps/slip-snapper-e2e/src/fixtures/Login.json
  frontend/apps/slip-snapper-e2e/src/fixtures/RecentReports.json
  frontend/apps/slip-snapper-e2e/src/fixtures/example.json
  frontend/apps/slip-snapper-e2e/src/fixtures/getAllReports.json
  frontend/apps/slip-snapper-e2e/src/integration/app.spec.ts
  frontend/apps/slip-snapper-e2e/src/integration/home-integration.spec.ts
  frontend/apps/slip-snapper-e2e/src/integration/login-integration.spec.ts
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/cypress.json
  frontend/package.json
Labels: priority:high, type:test, scope:feature

#252 ✨ (db queries) retrieve all the slips
  backend/api/apps/src/db.js
Labels: priority:high, scope:db, type:feature, scope:feature

#254 💄 (ui): Added confirmation for report deletion
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: type:enhancement, priority:medium, scope:ui

#255 (Feature/api) Added user login data
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/components/FetchData.js
  frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
  frontend/apps/slip-snapper/src/app/components/ReportTotal.tsx
  frontend/apps/slip-snapper/src/app/components/UserStats.tsx
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: priority:low, scope:api, type:change

#256 ✅ (testing): more integration tests
  frontend/apps/slip-snapper-e2e/src/fixtures/getBudget.json
  frontend/apps/slip-snapper-e2e/src/fixtures/getItems.json
  frontend/apps/slip-snapper-e2e/src/fixtures/getReport.json
  frontend/apps/slip-snapper-e2e/src/fixtures/getUserStats.json
  frontend/apps/slip-snapper-e2e/src/integration/home-integration.spec.ts
  frontend/apps/slip-snapper-e2e/src/integration/login-integration.spec.ts
  frontend/apps/slip-snapper-e2e/src/integration/navigation-integration.spec.ts
Labels: priority:high, type:test, scope:feature

#257 ✨ (feature): Renders users slips
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/item.js
  backend/api/apps/src/routes/slips.js
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/App.tsx
  frontend/apps/slip-snapper/src/app/components/FetchData.js
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
Labels: priority:medium, scope:ui, type:feature

#258 🎨 (feature/api) Frontend will now use the local storage of user
  backend/api/apps/src/routes/report.js
  frontend/.gitignore
  frontend/apps/slip-snapper/src/app/components/FetchData.js
  frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
  frontend/apps/slip-snapper/src/app/components/ReportTotal.tsx
  frontend/apps/slip-snapper/src/app/components/UserStats.tsx
  frontend/apps/slip-snapper/src/app/components/usePhotoGallery.js
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: priority:low, scope:api, type:bug, type:change

#259 💄 (ui): Added Alerts in Entry pages
  frontend/apps/slip-snapper/src/app/components/FetchData.js
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
Labels: type:enhancement, priority:medium, scope:ui

#260 🎨 (feature/api) Added api call to update slip and items
  backend/api/apps/src/routes/item.js
  backend/api/apps/tests/routes/items.test.js
Labels: priority:low, scope:api, type:change

#261 :sparkles: (db queries) set specific budgets
  backend/api/apps/src/db.js
Labels: priority:high, scope:db, type:feature, scope:feature

#262 💄 (ui): Dynamically render this week's reports
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/report.js
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
  frontend/apps/slip-snapper/src/app/components/ViewReportItem.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
Labels: priority:low, scope:ui, type:feature

#263 🐛 (bug): Input validation for AddEntry
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/theme/profile.css
Labels: priority:low, scope:ui, type:bug

#264 🐛 (bug): Input validation for EditSlip and EditReeceipt
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
Labels: priority:low, scope:ui, type:bug

#265 ✨ :(db queries) today's reports for the home page
  backend/api/apps/src/db.js
Labels: priority:high, scope:db, type:feature, scope:feature

#266 🐛 (feature/api): Fixed bug for pdf functionality
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/S3Bucket.js
  backend/api/apps/src/routes/item.js
  backend/api/apps/src/routes/report.js
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/components/FetchData.js
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: type:enhancement, priority:low, scope:api, type:bug, type:change

#267 ♻️ (refactor): Refactored ViewReports
  frontend/apps/slip-snapper/src/app/components/ReportTotal.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/apps/slip-snapper/src/app/theme/reportTotal.css
  frontend/apps/slip-snapper/src/app/theme/viewReports.css
Labels: priority:low, scope:ui, type:change

#268 💄 (ui): Render Todays expenditure
  backend/api/apps/src/routes/report.js
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
Labels: priority:low, scope:ui, type:feature

#269 ✨ (db queries) delete multiple items
  backend/api/apps/src/db.js
Labels: priority:high, scope:db, type:feature, scope:feature

#271 🚧 (ui): Updated Personal Budget UI
  backend/api/apps/src/routes/report.js
  frontend/apps/slip-snapper/src/app/components/UserStats.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
Labels: priority:medium, type:feature, scope:feature

#272 🎨 (feature/api): update the fronetned to use the correct data
  backend/api/apps/server.js
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/item.js
  backend/api/apps/src/routes/report.js
  backend/api/apps/tests/routes/report.test.js
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/components/UserStats.tsx
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
Labels: type:enhancement, priority:low, scope:api, type:change, type:test

#273 💄 (ui): Updated login and register UI
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/app/theme/login.css
  frontend/apps/slip-snapper/src/app/theme/register.css
Labels: priority:low, scope:ui, type:change

#274 💄 (ui): Correctly renders slips on pages
  frontend/apps/slip-snapper/src/app/components/FetchData.js
  frontend/apps/slip-snapper/src/app/components/SlipItems.tsx
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
  frontend/apps/slip-snapper/src/app/pages/Receipts.tsx
Labels: type:enhancement, priority:low, scope:ui

#276 🎨 (feature/api) Budgets now use the respective values
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/report.js
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/components/Budget.tsx
  frontend/apps/slip-snapper/src/app/components/UserStats.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
Labels: priority:low, scope:api, type:change

#275 ✨ ✅ New tests and fixes
  .github/workflows/FrontendCItest.yml
  .github/workflows/index.yml
  backend/api/apps/src/db.js
  frontend/android/app/src/main/AndroidManifest.xml
  frontend/apps/slip-snapper-e2e/src/fixtures/TodayHomePage.json
  frontend/apps/slip-snapper-e2e/src/fixtures/getBudget.json
  frontend/apps/slip-snapper-e2e/src/fixtures/getSlips.json
  frontend/apps/slip-snapper-e2e/src/integration/home-integration.spec.ts
  frontend/apps/slip-snapper-e2e/src/integration/login-integration.spec.ts
  frontend/apps/slip-snapper-e2e/src/integration/navigation-integration.spec.ts
  frontend/apps/slip-snapper-e2e/src/support/index.ts
  frontend/apps/slip-snapper/src/app/components/SlipItems.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/apps/slip-snapper/src/app/theme/viewReports.css
Labels: type:enhancement, priority:high, scope:cicd, type:bug, type:feature, type:test, scope:feature

#277 🎨 (feature/api): PDF generation refactored
  backend/api/apps/src/routes/report.js
  backend/api/package.json
  backend/api/yarn.lock
Labels: type:enhancement, priority:medium, scope:api

#278 🐛 (bug): Fixed Delete report bug
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: type:enhancement, priority:low, scope:ui

#279 💄 (ui): General UI fixes
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/Tests/__snapshots__/App.spec.tsx.snap
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/theme/variables.css
Labels: type:enhancement, priority:low, scope:ui

#281 🐛 (ui): Dynamic User's Name on Profile Page
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
Labels: priority:low, scope:ui, type:change

#282 💄 (ui): Added toasts to the home page
  frontend/apps/slip-snapper/src/app/components/ViewReportItem.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
Labels: type:enhancement, priority:low, scope:ui

#283 🐛 (bug): Fixed bug on EditSlip page
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
Labels: priority:low, type:bug, scope:feature

#284 🐛 (feature/api): Temp fix for double deleting on edit receipt
  backend/api/apps/src/db.js
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
Labels: priority:low, scope:api, type:bug

#285 ✨ (feature): Various fixes and addtions
  frontend/apps/slip-snapper-e2e/src/integration/home-integration.spec.ts
  frontend/apps/slip-snapper-e2e/src/integration/navigation-integration.spec.ts
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/components/Budget.tsx
  frontend/apps/slip-snapper/src/app/components/NavButtons.tsx
  frontend/apps/slip-snapper/src/app/components/SlipItems.tsx
  frontend/apps/slip-snapper/src/app/components/UserStats.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: type:enhancement, priority:high, type:change, type:test, scope:feature

#286 💄 (ui): Added slip photo to the EditSlip page
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/apps/slip-snapper/src/app/theme/editSlip.css
Labels: priority:low, scope:ui, type:feature

#287 💄 (ui): Logo and PWA icons
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/assets/icon/512px-tp-white.svg
  frontend/apps/slip-snapper/src/assets/icon/512px-tp.svg
  frontend/apps/slip-snapper/src/assets/icon/favicon.png
  frontend/apps/slip-snapper/src/assets/icon/icon.png
  frontend/apps/slip-snapper/src/assets/icon/maskable_icon.png
  frontend/apps/slip-snapper/src/assets/icon/maskable_icon_x128.png
  frontend/apps/slip-snapper/src/assets/icon/maskable_icon_x192.png
  frontend/apps/slip-snapper/src/assets/icon/maskable_icon_x384.png
  frontend/apps/slip-snapper/src/assets/icon/maskable_icon_x48.png
  frontend/apps/slip-snapper/src/assets/icon/maskable_icon_x72.png
  frontend/apps/slip-snapper/src/assets/icon/maskable_icon_x96.png
Labels: type:enhancement, priority:low, scope:ui

#288 Feature/documentation
  README.md
Labels: type:documentation, priority:high, scope:repository
