Repository COS301-SE-2022/Slip-Snapper, pull requests merged in 2022-05, with the labels that each got.

#1 :memo: (repo): Added code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#7 :memo: (Repo) : Added ReadMe.md
  README.md
Labels: documentation

#9 :sparkles: (repo): Created workspace
  .editorconfig
  .eslintrc.json
  .gitignore
  .prettierignore
  .prettierrc
  .vscode/extensions.json
  apps/.gitkeep
  apps/slip-snapper-e2e/.eslintrc.json
  apps/slip-snapper-e2e/cypress.json
  apps/slip-snapper-e2e/project.json
  apps/slip-snapper-e2e/src/fixtures/example.json
  apps/slip-snapper-e2e/src/integration/app.spec.ts
  apps/slip-snapper-e2e/src/support/app.po.ts
  apps/slip-snapper-e2e/src/support/commands.ts
  apps/slip-snapper-e2e/src/support/index.ts
  apps/slip-snapper-e2e/tsconfig.json
  apps/slip-snapper/.babelrc
  apps/slip-snapper/.browserslistrc
  apps/slip-snapper/.eslintrc.json
  apps/slip-snapper/.gitignore
  apps/slip-snapper/capacitor.config.ts
  apps/slip-snapper/ionic.config.json
  apps/slip-snapper/jest.config.js
  apps/slip-snapper/package.json
  apps/slip-snapper/project.json
  apps/slip-snapper/src/app/App.spec.tsx
  apps/slip-snapper/src/app/App.tsx
  apps/slip-snapper/src/app/components/ExploreContainer.css
  apps/slip-snapper/src/app/components/ExploreContainer.tsx
  apps/slip-snapper/src/app/nx-welcome.tsx
  apps/slip-snapper/src/app/pages/Home.css
  apps/slip-snapper/src/app/pages/Home.tsx
  apps/slip-snapper/src/app/theme/variables.css
  apps/slip-snapper/src/assets/.gitkeep
  apps/slip-snapper/src/assets/icon/favicon.png
  apps/slip-snapper/src/assets/icon/icon.png
  apps/slip-snapper/src/environments/environment.prod.ts
  apps/slip-snapper/src/environments/environment.ts
  apps/slip-snapper/src/index.html
  apps/slip-snapper/src/main.tsx
  apps/slip-snapper/src/manifest.json
  apps/slip-snapper/src/polyfills.ts
  apps/slip-snapper/src/styles.css
  apps/slip-snapper/tsconfig.app.json
  apps/slip-snapper/tsconfig.json
  apps/slip-snapper/tsconfig.spec.json
  babel.config.json
  jest.config.js
  jest.preset.js
  libs/.gitkeep
  nx.json
  package-lock.json
  package.json
  tools/generators/.gitkeep
  tools/tsconfig.tools.json
  tsconfig.base.json
  workspace.json
Labels: enhancement

#11 :memo: (repo) : Updated ReadMe.md
  README.md
Labels: type:documentation, priority:low, scope:repository

#15 :memo: (repo) : Updated ReadMe.md
  README.md
Labels: type:documentation, priority:low, scope:repository

#16 :white_check_mark: (cicd): Created Meta tag workflow
  .github/workflow/MetaTest.yml
Labels: priority:low, scope:repository, scope:cicd, type:test

#20 :sparkles: (repo): Added yarn to repo
  package-lock.json
  package.json
  yarn.lock
Labels: priority:medium, scope:repository, type:feature

#23 :recycle: (repo): Complete restructure of code base
  apps/slip-snapper/src/app/components/ExploreContainer.tsx
  frontend/.editorconfig
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.prettierrc
  frontend/apps/.gitkeep
  frontend/apps/slip-snapper-e2e/.eslintrc.json
  frontend/apps/slip-snapper-e2e/cypress.json
  frontend/apps/slip-snapper-e2e/project.json
  frontend/apps/slip-snapper-e2e/src/fixtures/example.json
  frontend/apps/slip-snapper-e2e/src/integration/app.spec.ts
  frontend/apps/slip-snapper-e2e/src/support/app.po.ts
  frontend/apps/slip-snapper-e2e/src/support/commands.ts
  frontend/apps/slip-snapper-e2e/src/support/index.ts
  frontend/apps/slip-snapper-e2e/tsconfig.json
  frontend/apps/slip-snapper/.babelrc
  frontend/apps/slip-snapper/.browserslistrc
  frontend/apps/slip-snapper/.eslintrc.json
  frontend/apps/slip-snapper/.gitignore
  frontend/apps/slip-snapper/capacitor.config.ts
  frontend/apps/slip-snapper/ionic.config.json
  frontend/apps/slip-snapper/jest.config.js
  frontend/apps/slip-snapper/package.json
  frontend/apps/slip-snapper/project.json
  frontend/apps/slip-snapper/src/app/App.spec.tsx
  frontend/apps/slip-snapper/src/app/App.tsx
  frontend/apps/slip-snapper/src/app/components/ExploreContainer.css
  frontend/apps/slip-snapper/src/app/components/ExploreContainer.tsx
  frontend/apps/slip-snapper/src/app/components/TakePictureButton.tsx
  frontend/apps/slip-snapper/src/app/nx-welcome.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.css
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/theme/variables.css
  frontend/apps/slip-snapper/src/assets/.gitkeep
  frontend/apps/slip-snapper/src/assets/icon/favicon.png
  frontend/apps/slip-snapper/src/assets/icon/icon.png
  frontend/apps/slip-snapper/src/environments/environment.prod.ts
  frontend/apps/slip-snapper/src/environments/environment.ts
  frontend/apps/slip-snapper/src/hooks/usePhotoGallery.ts
  frontend/apps/slip-snapper/src/index.html
  frontend/apps/slip-snapper/src/main.tsx
  frontend/apps/slip-snapper/src/manifest.json
  frontend/apps/slip-snapper/src/polyfills.ts
  frontend/apps/slip-snapper/src/styles.css
  frontend/apps/slip-snapper/tsconfig.app.json
  frontend/apps/slip-snapper/tsconfig.json
  frontend/apps/slip-snapper/tsconfig.spec.json
  frontend/babel.config.json
  frontend/jest.config.js
  frontend/jest.preset.js
  frontend/libs/.gitkeep
  frontend/nx.json
  frontend/package.json
  frontend/tools/generators/.gitkeep
  frontend/tools/tsconfig.tools.json
  frontend/tsconfig.base.json
  frontend/workspace.json
  frontend/yarn.lock
Labels: type:enhancement, priority:high, scope:repository, scope:api, type:change

#25 🐛 (cicd): Removed e2e
  .github/workflows/CItest.yml
  .github/workflows/index.yml
Labels: priority:medium, scope:cicd, type:bug

#26 ✨ (backend-api): Added example api call
  .gitignore
  .prettierignore
  backend/api/database.json
  backend/api/index.ts
  backend/api/package.json
  backend/api/yarn.lock
Labels: priority:medium, scope:api, type:feature

#32 ✨ (feature/side-menu): Added ViewReports page
  frontend/apps/slip-snapper/package.json
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: priority:medium, scope:ui, type:feature

#33 🐛 (cicd): fixed index.yml directory for backend
  .github/workflows/BackendCITest.yml
  .github/workflows/index.yml
  frontend/apps/slip-snapper/src/app/App.tsx
Labels: priority:high, scope:cicd, type:bug

#34 🎨 (feature-api): Added api call for getting user item
  backend/api/database.json
  backend/api/index.ts
  backend/api/package.json
  backend/api/src/index.ts
  backend/api/src/items.json
  backend/api/src/users.json
  backend/api/yarn.lock
Labels: type:enhancement, priority:high, scope:api

#35 ✨ (ui): Added menu
  frontend/apps/slip-snapper/src/app/App.tsx
  frontend/apps/slip-snapper/src/app/components/Menu.tsx
  frontend/apps/slip-snapper/src/app/components/NavButtons.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: priority:medium, scope:ui, type:feature

#36 🎨 (feature-api): added the API calls for item
  backend/api/src/index.ts
  backend/api/src/items.json
Labels: type:enhancement, priority:medium, scope:api

#43 💄 (ui): Added mock components
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
Labels: type:enhancement, priority:low, scope:ui

#44 🎨 (feature-api): added the user api calls
  backend/api/src/index.ts
  backend/api/src/users.json
Labels: type:enhancement, priority:medium, scope:api

#45 ✨ (feature): Added TakePicture functionality
  .github/workflows/MetaTest.yml
  frontend/apps/slip-snapper/src/app/components/TakePictureButton.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/hooks/usePhotoGallery.ts
Labels: priority:high, type:feature, scope:feature

#47 ✨ (ui): Added EditItem page
  frontend/apps/slip-snapper/src/app/App.tsx
  frontend/apps/slip-snapper/src/app/components/Menu.tsx
  frontend/apps/slip-snapper/src/app/components/NavButtons.tsx
  frontend/apps/slip-snapper/src/app/pages/EditItem.tsx
  frontend/apps/slip-snapper/src/app/testData.json
Labels: priority:medium, scope:ui, type:feature

#48 :bug: (feature): Fixed take picture option
  frontend/apps/slip-snapper/src/hooks/usePhotoGallery.ts
  frontend/apps/slip-snapper/src/main.tsx
  frontend/package.json
  frontend/yarn.lock
Labels: priority:high, type:bug, type:feature, scope:feature

#49 🎨 (feature-api): updated the add and update item call
  backend/api/package.json
  backend/api/src/index.js
  backend/api/src/items.json
Labels: type:enhancement, priority:high, scope:api

#50 :recycle: (repo): setup backend nx workspace
  backend/api/.editorconfig
  backend/api/.gitignore
  backend/api/.prettierrc
  backend/api/.vscode/extensions.json
  backend/api/README.md
  backend/api/apps/.gitkeep
  backend/api/apps/src/index.js
  backend/api/apps/src/items.json
  backend/api/apps/src/users.json
  backend/api/libs/.gitkeep
  backend/api/nx.json
  backend/api/package.json
  backend/api/tools/generators/.gitkeep
  backend/api/tools/tsconfig.tools.json
  backend/api/tsconfig.base.json
  backend/api/workspace.json
  backend/api/yarn.lock
Labels: priority:medium, scope:repository, type:change

#51 :white_check_mark: (cicd): Added yarn test for Backend workflow
  .github/workflows/BackendCITest.yml
  .github/workflows/index.yml
Labels: priority:medium, scope:cicd, type:test

#53 🎨 (feature-api): Updated api to account for change in "database"
  backend/api/apps/src/index.js
Labels: type:enhancement, priority:medium, scope:api

#54 ✅ (cicd): Added codcov
  .github/workflows/FrontendCItest.yml
  .github/workflows/full.yml
  README.md
  frontend/apps/slip-snapper/src/app/pages/EditItem.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.css
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/jest.preset.js
Labels: priority:high, scope:cicd, type:test

#56 💄 (ui): EditItem page styling updated
  frontend/apps/slip-snapper/src/app/App.tsx
  frontend/apps/slip-snapper/src/app/components/FetchData.js
  frontend/apps/slip-snapper/src/app/pages/FetchData.css
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
Labels: type:enhancement, priority:medium, scope:ui

#57 ✅ (feature-api): Added unit test for the user querys of the api
  backend/api/apps/server.js
  backend/api/apps/src/index.js
  backend/api/apps/tests/index.test.js
  backend/api/package.json
Labels: priority:medium, scope:api, type:test

#58 :white_check_mark: (feature): Added some Jest Tests
  frontend/apps/slip-snapper/src/app/App.spec.tsx
  frontend/apps/slip-snapper/src/app/__snapshots__/App.spec.tsx.snap
  frontend/package.json
  frontend/yarn.lock
Labels: priority:high, type:test, scope:feature

#59 ✨ (ui) Added register page
  frontend/apps/slip-snapper/src/app/App.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/app/theme/variables.css
Labels: priority:low, type:feature, scope:feature

#61 ✅ (feature-api): added unit test for all the item api calls
  backend/api/apps/src/index.js
  backend/api/apps/tests/index.test.js
Labels: priority:medium, scope:api, type:test

#63 💄 (ui): added username component
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
Labels: type:enhancement, priority:medium, scope:ui, type:feature

#64 💄 (ui): Added password component
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
Labels: priority:medium, scope:ui, type:feature

#67 🎨 (ui-api): Connected the edit item ui to the api call
  .github/workflows/index.yml
  backend/api/apps/src/index.js
  backend/api/package.json
  frontend/apps/slip-snapper/src/app/components/FetchData.js
Labels: type:enhancement, priority:medium, scope:ui, scope:api

#68 :white_check_mark: (test): Added more Jest tests
  README.md
  frontend/apps/slip-snapper/src/app/App.spec.tsx
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/Tests/__snapshots__/App.spec.tsx.snap
Labels: priority:high, type:test, scope:feature

#69 💄 (ui): Corrected CSS Errors
  frontend/apps/slip-snapper/src/app/pages/LoginRegister.css
  frontend/apps/slip-snapper/src/app/pages/Register.css
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/app/theme/variables.css
Labels: type:enhancement, priority:low, scope:ui

#70 💄 (ui): Functions for "Generate Report" buttons
  backend/api/apps/src/items.json
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
Labels: type:enhancement, priority:medium, scope:ui

#71 🎨 (ui-api): connected frontend and backend for generate reports
  backend/api/.vscode/extensions.json
  backend/api/apps/src/index.js
  backend/api/apps/src/items.json
  backend/api/apps/tests/index.test.js
  backend/api/libs/.gitkeep
  backend/api/tools/generators/.gitkeep
  backend/api/tools/tsconfig.tools.json
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
Labels: priority:medium, scope:ui, scope:api, type:feature

#72 :pencil: (documentation): Added some commands in Readme
  backend/api/README.md
  frontend/README.md
Labels: type:documentation, priority:low, scope:repository

#73 💄 (ui): Styling for Login and Register
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/LoginRegister.css
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
Labels: priority:high, scope:ui, type:feature, scope:feature

#75 🐛 (ui) Fixed UI for Login and Register
  README.md
  frontend/apps/slip-snapper/src/app/App.tsx
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/LoginRegister.css
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/app/theme/LoginRegister.css
Labels: type:documentation, priority:high, scope:repository, scope:ui, type:bug

#76 📝(repo): Added Demo 1 Recording to README.md
  README.md
Labels: type:documentation, priority:high, scope:repository

#78 :sparkles: (ocr): Integrated Tesseract worker
  frontend/apps/slip-snapper/src/hooks/OCR.tsx
  frontend/apps/slip-snapper/src/hooks/usePhotoGallery.ts
  frontend/package.json
  frontend/yarn.lock
Labels: priority:high, type:feature, scope:feature

#79 :construction: (takepic): Rework to return DataUrl
  frontend/apps/slip-snapper/src/app/Tests/__snapshots__/App.spec.tsx.snap
  frontend/apps/slip-snapper/src/app/components/TakePictureButton.tsx
  frontend/apps/slip-snapper/src/hooks/usePhotoGallery.ts
Labels: priority:high, type:feature, scope:feature

#80 :sparkles: (ocr): Used Tesseract Text
  frontend/apps/slip-snapper/src/app/components/TakePictureButton.tsx
Labels: priority:medium, type:feature, scope:feature

#82 🎨 (feature/api) Added the skeleton of login call
  backend/api/apps/server.js
  backend/api/apps/src/index.js
  backend/api/apps/tests/index.test.js
  backend/api/package.json
Labels: type:enhancement, priority:low, scope:api, type:change

#83 💄 (ui): Added ui to the profile page
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
Labels: priority:medium, scope:ui, type:feature

#84 🎨 (feature-api): Updated the generate report api call
  backend/api/apps/src/index.js
  backend/api/apps/tests/index.test.js
  frontend/apps/slip-snapper/src/app/components/FetchData.js
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
Labels: type:enhancement, priority:low, scope:ui, scope:api, type:change, type:test

#87 🎨 (Feature/api): Added frontend functions for authentication functionality
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
Labels: priority:low, scope:ui, scope:api, type:change

#88 💄 (ui): Updated UI on the profile page
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
Labels: type:enhancement, priority:medium, scope:ui

#90 :sparkles: (db): prisma setup
  backend/database/prisma/.gitignore
  backend/database/prisma/package.json
  backend/database/prisma/prisma/migrations/20220529175222_init/migration.sql
  backend/database/prisma/prisma/migrations/migration_lock.toml
  backend/database/prisma/yarn.lock
Labels: priority:medium, scope:db, type:feature

#92 🎨 (Feature/api): Updated API to be level 1 compliant
  backend/api/apps/src/index.js
  backend/api/apps/tests/index.test.js
  frontend/apps/slip-snapper/src/app/components/FetchData.js
Labels: type:enhancement, priority:low, scope:api, type:change, type:test

#93 ✨ (db) setup Docker
  backend/database/prisma/docker-compose.yml
Labels: priority:medium, scope:db, type:feature

#94 :lipstick: (ui): Updated UI of Login Page
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/app/theme/LoginRegister.css
  frontend/apps/slip-snapper/src/assets/icon/temp_logo.png
Labels: type:enhancement, priority:low, scope:ui

#95 :package: : (db) schema update
  backend/database/prisma/prisma/migrations/20220529191053_init/migration.sql
Labels: priority:medium, scope:db, type:feature

#96 :sparkles: (db) configure prisma
  backend/database/prisma/tsconfig.json
Labels: priority:medium, scope:db, type:feature

#97 :sparkles: (db): create db
  backend/database/prisma/postgresql/01-init.sh
Labels: priority:medium, scope:db, type:feature

#98 ✨ (db) create db schemas
  backend/database/prisma/prisma/schema.prisma
Labels: priority:medium, scope:db, type:feature

#99 💄(ui): Added css file and logout for Profile page
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/theme/profile.css
Labels: type:enhancement, priority:low, scope:ui

#106 💄(ui): Added Ui to the ViewReports page
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/apps/slip-snapper/src/app/theme/viewReports.css
Labels: type:enhancement, priority:medium, scope:ui

#107 🎨 (feature/api) : Added ocr call to api
  backend/api/apps/src/index.js
  backend/api/apps/tests/index.test.js
  frontend/apps/slip-snapper/src/hooks/OCR.tsx
Labels: type:enhancement, priority:low, scope:api, type:test

#108 :lipstick: (ui): Updated Register Page UI
  README.md
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
Labels: type:enhancement, priority:low, scope:ui

#109 🎨 (Feature/api): Moved api calls to the router files
  backend/api/apps/src/index.js
  backend/api/apps/src/routes/auth.js
  backend/api/apps/src/routes/item.js
  backend/api/apps/src/routes/ocr.js
  backend/api/apps/src/routes/report.js
  backend/api/apps/tests/index.test.js
  backend/api/package.json
  frontend/apps/slip-snapper/src/app/components/FetchData.js
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/hooks/OCR.tsx
Labels: type:enhancement, priority:low, scope:api, type:change

#111 :fire: ➖ (db) Remove docker dependency
  backend/database/prisma/docker-compose.yml
  backend/database/prisma/postgresql/01-init.sh
Labels: priority:low, scope:db, type:change, type:feature
