Repository COS301-SE-2022/Slip-Snapper, pull requests merged in 2022-09, with the labels that each got.

#360 💄 (ui): Search functionality for Receipts
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/report.js
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/components/Budget.tsx
  frontend/apps/slip-snapper/src/app/components/SlipItems.tsx
  frontend/apps/slip-snapper/src/app/components/UserStats.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/apps/slip-snapper/src/app/theme/SlipItems.css
Labels: type:enhancement, priority:medium, scope:ui

#367 💄 (ui): Mock Graphs in Home Page
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/item.js
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/apps/slip-snapper/src/app/theme/home.css
  frontend/package.json
  frontend/yarn.lock
Labels: priority:medium, scope:ui, scope:api, type:feature

#369 ✨ (data analysis) wow feature, item averages across stores
  backend/api/apps/src/db.js
Labels: priority:high, scope:db, type:feature, scope:feature

#370 💄 (ui): Dynamically Renders Graphs
  backend/api/apps/src/routes/item.js
  backend/api/apps/src/routes/report.js
  frontend/apps/slip-snapper/src/app/components/Graph.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/theme/graph.css
Labels: priority:medium, scope:ui, type:feature

#371 🚧 (ui): Graph style update
  frontend/apps/slip-snapper/src/app/components/Graph.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/theme/graph.css
  frontend/apps/slip-snapper/src/app/theme/home.css
  frontend/apps/slip-snapper/src/app/theme/variables.css
Labels: type:enhancement, priority:low, scope:ui

#372 🐛 (bug): Fixed category budgets bug
  frontend/apps/slip-snapper/src/app/components/Budget.tsx
Labels: type:enhancement, priority:low, scope:ui

#373 (Feature/documentation): Minor Updates To readme Structure
  README.md
Labels: type:documentation, priority:low, scope:repository

#379 ✨(ui): Added ForgotPassword page
  .github/workflows/FrontendCItest.yml
  .github/workflows/index.yml
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/App.tsx
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/pages/ForgotPass.tsx
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/app/theme/login-register.css
Labels: priority:medium, scope:ui, type:change, type:feature, type:test, scope:feature

#383 🐛 (bug): Bug fixes in Search and Auth files
  backend/api/apps/src/routes/auth.js
  frontend/apps/slip-snapper/src/app/components/SlipItems.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
Labels: priority:medium, scope:ui, type:bug

#382 ✨ (various): Fixes and additions
  backend/api/apps/src/imageProcessor.js
  backend/api/apps/src/routes/ocr.js
  backend/api/apps/src/routes/report.js
  backend/api/apps/tests/routes/ocr.test.js
  backend/api/apps/textProcessor/text_parser/parser.js
  backend/api/package.json
  backend/api/yarn.lock
  frontend/android/.gitignore
  frontend/android/.idea/.gitignore
  frontend/android/.idea/deploymentTargetDropDown.xml
  frontend/android/.idea/jarRepositories.xml
  frontend/android/app/build.gradle
  frontend/android/app/capacitor.build.gradle
  frontend/android/app/src/main/AndroidManifest.xml
  frontend/android/app/src/main/assets/capacitor.plugins.json
  frontend/android/app/src/main/res/values/styles.xml
  frontend/android/app/src/main/res/xml/config.xml
  frontend/android/build.gradle
  frontend/android/capacitor.settings.gradle
  frontend/android/gradle.properties
  frontend/android/gradle/wrapper/gradle-wrapper.jar
  frontend/android/gradle/wrapper/gradle-wrapper.properties
  frontend/android/gradlew
  frontend/android/variables.gradle
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/Tests/Home.spec.tsx
  frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
  frontend/apps/slip-snapper/src/app/components/usePhotoGallery.js
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/ios/App/App/config.xml
  frontend/ios/App/Podfile
  frontend/package.json
  frontend/yarn.lock
Labels: type:enhancement, priority:high, scope:ui, scope:api, type:bug, type:change, type:feature, scope:feature

#385 (Feature/categoriser): First itteration of item categorsier
  backend/api/.gitignore
  backend/api/apps/itemCategoriser/categorizer.js
  backend/api/apps/itemCategoriser/dataSet_Generation/generator.js
  backend/api/apps/itemCategoriser/itemCategoriser.js
  backend/api/apps/itemCategoriser/itemcategory/model.json
  backend/api/apps/itemCategoriser/itemcategory/weights.bin
  backend/api/apps/src/routes/ocr.js
  backend/api/apps/textProcessor/processor.js
  backend/api/apps/textProcessor/text_parser/parser.js
  backend/api/package.json
  backend/api/yarn.lock
Labels: type:enhancement, priority:medium, scope:api

#387 :bug: crash and other bug fixes
  frontend/apps/slip-snapper/src/app/components/EditBudgets.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: priority:high, type:bug, scope:feature

#388 💄 (ui): Various UI updates
  frontend/apps/slip-snapper/src/app/components/TakePictureButton.tsx
  frontend/apps/slip-snapper/src/app/components/UserStats.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/theme/fab-home.css
  frontend/apps/slip-snapper/src/app/theme/home.css
  frontend/apps/slip-snapper/src/app/theme/profile.css
  frontend/apps/slip-snapper/src/app/theme/user-stats.css
Labels: type:enhancement, priority:low, scope:ui

#389 💄 (ui): Totals filtering on Receipts page
  backend/api/apps/src/db.js
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/components/Budget.tsx
  frontend/apps/slip-snapper/src/app/components/EditBudgets.tsx
  frontend/apps/slip-snapper/src/app/components/SlipItems.tsx
  frontend/apps/slip-snapper/src/app/components/UserStats.tsx
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/apps/slip-snapper/src/app/theme/SlipItems.css
  frontend/apps/slip-snapper/src/app/theme/profile.css
Labels: type:enhancement, priority:medium, scope:ui

#392 🐛 dates adjusted to be relative to the current week and month
  backend/api/apps/src/db.js
Labels: type:enhancement, priority:high, scope:db, type:bug, type:feature

#393 🐛 (db queries) added date constraints to budgets
  backend/api/apps/src/db.js
Labels: priority:medium, scope:db, type:bug, type:change

#394 💄 (ui): Category budgets now use correct totals
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/components/Budget.tsx
  frontend/apps/slip-snapper/src/app/components/ProfileBarGraph.tsx
  frontend/apps/slip-snapper/src/app/components/SlipItems.tsx
  frontend/apps/slip-snapper/src/app/components/UserStats.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/theme/SlipItems.css
Labels: type:enhancement, priority:medium, scope:ui

#395 🐛 (data analytics) prevent null values
  backend/api/apps/src/db.js
Labels: priority:medium, scope:db, type:bug, type:feature, scope:feature

#396 🚧 (ui): Receipts Page refactor
  frontend/apps/slip-snapper/src/app/components/SlipItems.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/theme/slip-items.css
Labels: type:enhancement, priority:medium, scope:ui, type:change, scope:feature

#397 🐛 (db queries) todays total only accounts for today
  backend/api/apps/src/db.js
Labels: priority:medium, scope:db, type:bug

#398 💄 (ui): Login/Register updates
  frontend/apps/slip-snapper/src/app/components/SlipItems.tsx
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/app/theme/login-register.css
  frontend/apps/slip-snapper/src/app/theme/slip-items.css
Labels: type:enhancement, priority:medium, scope:ui

#399 (Feature/spreadsheet): ability to generate and return excel files
  backend/api/apps/src/routes/report.js
  backend/api/package.json
  backend/api/yarn.lock
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: type:enhancement, priority:low, scope:api

#401 💄 (ui): Added Category Pie Chart to Profile Page
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/components/ProfileBarGraph.tsx
  frontend/apps/slip-snapper/src/app/components/ProfilePieChart.tsx
  frontend/apps/slip-snapper/src/app/components/SlipItems.tsx
  frontend/apps/slip-snapper/src/app/components/UserStats.tsx
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/theme/slip-items.css
Labels: type:enhancement, priority:low, scope:ui

#402 (Feature/spreadsheet): Minor fixes to spreadsheet functionality
  backend/api/apps/src/routes/report.js
  backend/api/apps/src/token.js
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: type:enhancement, priority:low, scope:api

#403 🐛 (feature/reports) updated reports to return items within a given time frame
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/report.js
Labels: priority:medium, scope:db, type:bug, type:feature, scope:feature

#406 💄 (ui): Updated UI of Reports Page
  frontend/apps/slip-snapper/src/app/components/SlipItems.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/apps/slip-snapper/src/app/theme/viewReports.css
Labels: type:enhancement, priority:medium, scope:ui

#407 🐛 (db queries) daily report fixed
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/report.js
Labels: priority:medium, scope:db, type:bug, type:feature

#408 (Feature/spreadsheet): fixed spreadsheet generation bug
  backend/api/apps/src/routes/report.js
Labels: priority:low, scope:api, type:bug

#409 ✅ (testing): provision for component tests
  frontend/apps/slip-snapper/src/app/tests/components/Budget.test.tsx
  frontend/apps/slip-snapper/src/app/tests/components/Graph.test.tsx
  frontend/apps/slip-snapper/src/app/tests/components/__snapshots__/Budget.test.tsx.snap
  frontend/apps/slip-snapper/src/app/tests/components/__snapshots__/Graph.test.tsx.snap
  frontend/apps/slip-snapper/src/app/tests/components/usePhotoGallery.test.js
  frontend/apps/slip-snapper/src/app/tests/pages/App.spec.tsx
  frontend/apps/slip-snapper/src/app/tests/pages/Home.spec.tsx
  frontend/apps/slip-snapper/src/app/tests/pages/__snapshots__/App.spec.tsx.snap
Labels: priority:medium, type:test, scope:feature

#411 (Feature/validation): updated endpoints and unit tests
  backend/api/apps/src/index.js
  backend/api/apps/src/routes/report.js
  backend/api/apps/src/routes/stats.js
  backend/api/apps/tests/routes/report.test.js
  backend/api/apps/tests/routes/stats.test.js
  frontend/apps/slip-snapper/src/api/apiCall.js
Labels: priority:low, scope:api, type:change, type:test

#412 💄 (ui): Minimal graph updates
  frontend/apps/slip-snapper/src/app/components/ProfilePieChart.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/apps/slip-snapper/src/app/theme/viewReports.css
Labels: type:enhancement, priority:low, scope:ui

#415 💄 (ui): Adjustments to Profile Page
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/stats.js
  frontend/apps/slip-snapper/src/app/components/ProfileBarGraph.tsx
  frontend/apps/slip-snapper/src/app/components/ProfilePieChart.tsx
  frontend/apps/slip-snapper/src/app/components/SlipItems.tsx
  frontend/apps/slip-snapper/src/app/components/UserStats.tsx
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/apps/slip-snapper/src/app/tests/components/__snapshots__/UserStats.test.tsx.snap
Labels: type:enhancement, priority:low, scope:ui

#416 💄 (ui): Reports timeframe toggle filter
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/apps/slip-snapper/src/app/theme/slip-items.css
  frontend/apps/slip-snapper/src/app/theme/viewReports.css
Labels: type:enhancement, priority:medium, scope:ui

#420 (Feature/validation): added validation to the report and stats
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/auth.js
  backend/api/apps/src/routes/ocr.js
  backend/api/apps/src/routes/report.js
  backend/api/apps/src/routes/stats.js
  backend/api/apps/tests/routes/auth.test.js
  backend/api/apps/tests/routes/report.test.js
  backend/api/apps/tests/routes/stats.test.js
Labels: type:enhancement, priority:low, scope:api

#422 💄 (ui): Updated UI in Home and Profile Page
  backend/api/apps/src/routes/stats.js
  frontend/apps/slip-snapper/src/app/components/Graph.tsx
  frontend/apps/slip-snapper/src/app/components/ProfileBarGraph.tsx
  frontend/apps/slip-snapper/src/app/components/ProfileLineGraph.tsx
  frontend/apps/slip-snapper/src/app/components/SlipItems.tsx
  frontend/apps/slip-snapper/src/app/components/UserStats.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/apps/slip-snapper/src/app/tests/components/__snapshots__/ProfileBarGraph.test.tsx.snap
  frontend/apps/slip-snapper/src/app/tests/components/__snapshots__/SlipItems.test.tsx.snap
  frontend/apps/slip-snapper/src/app/tests/components/__snapshots__/UserStats.test.tsx.snap
  frontend/apps/slip-snapper/src/app/theme/slip-items.css
  frontend/apps/slip-snapper/src/app/theme/user-stats.css
  frontend/apps/slip-snapper/src/app/theme/viewReports.css
Labels: type:enhancement, priority:medium, scope:ui, type:feature

#423 ✨ (db query) expenditure forecasting imlemented
  backend/api/apps/src/db.js
Labels: priority:high, scope:db, type:feature, scope:feature

#425 ✅ (tests): additional tests + fixes
  backend/api/apps/src/routes/auth.js
  backend/api/apps/src/routes/item.js
  backend/api/apps/src/routes/ocr.js
  backend/api/apps/src/routes/report.js
  backend/api/apps/src/routes/stats.js
  backend/api/apps/tests/parser.test.js
  backend/api/apps/tests/routes/auth.test.js
  backend/api/apps/textProcessor/text_parser/parser.js
  frontend/apps/slip-snapper-e2e/src/integration/home-integration.spec.ts
  frontend/apps/slip-snapper-e2e/src/integration/login-integration.spec.ts
  frontend/apps/slip-snapper-e2e/src/integration/navigation-integration.spec.ts
  frontend/apps/slip-snapper/src/app/components/Budget.tsx
  frontend/apps/slip-snapper/src/app/components/EditBudgets.tsx
  frontend/apps/slip-snapper/src/app/components/UserStats.tsx
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/apps/slip-snapper/src/app/tests/api/Session.test.js
  frontend/apps/slip-snapper/src/app/tests/api/apiCall.test.js
  frontend/apps/slip-snapper/src/app/tests/pages/EditReceipt.test.tsx
  frontend/package.json
  frontend/yarn.lock
Labels: priority:medium, type:bug, type:change, type:test, scope:feature

#426 🐛 (db queries) category returns budgets object
  backend/api/apps/src/db.js
Labels: priority:medium, scope:db, type:bug

#427 💄 (ui): This Weeks Expenditure
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/stats.js
  backend/api/apps/tests/routes/stats.test.js
  frontend/apps/slip-snapper/src/app/components/ProfileLineGraph.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/tests/api/apiCall.test.js
  frontend/apps/slip-snapper/src/app/tests/pages/Home.spec.tsx
  frontend/apps/slip-snapper/src/app/tests/pages/__snapshots__/EditReceipt.test.tsx.snap
Labels: priority:medium, scope:ui, type:feature

#429 🐛 (bug): Minor bug fix in EditSlip Page
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
Labels: priority:medium, scope:ui, type:bug

#430 ✨ (feature/validation) validation for auth.js complete
  backend/api/apps/src/routes/auth.js
  backend/api/apps/tests/routes/auth.test.js
  backend/api/prisma/migrations/20220922205543_final/migration.sql
  backend/api/prisma/schema.prisma
Labels: priority:high, scope:api, type:feature, scope:feature

#431 🐛 (ui): Bug fixes on Home, Profile pages
  frontend/apps/slip-snapper/src/app/components/EditBudgets.tsx
  frontend/apps/slip-snapper/src/app/components/Graph.tsx
  frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
  frontend/apps/slip-snapper/src/app/components/UserStats.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/apps/slip-snapper/src/app/tests/components/__snapshots__/EditBudgets.test.tsx.snap
  frontend/apps/slip-snapper/src/app/tests/components/__snapshots__/Graph.test.tsx.snap
  frontend/apps/slip-snapper/src/app/tests/components/__snapshots__/ReportItem.test.tsx.snap
  frontend/apps/slip-snapper/src/app/theme/home.css
  frontend/apps/slip-snapper/src/app/theme/profile.css
  frontend/apps/slip-snapper/src/app/theme/reportItem.css
  frontend/apps/slip-snapper/src/app/theme/user-stats.css
Labels: priority:medium, scope:ui, type:bug

#432 🔒️ (validation): Password input validation
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/app/tests/pages/App.spec.tsx
Labels: priority:medium, scope:ui, type:feature

#433 🐛 (ui): UI bug fixes on Login/Register/Home pages
  frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/app/tests/components/__snapshots__/ReportItem.test.tsx.snap
  frontend/apps/slip-snapper/src/app/theme/home.css
  frontend/apps/slip-snapper/src/app/theme/login-register.css
  frontend/apps/slip-snapper/src/app/theme/reportItem.css
Labels: priority:medium, priority:low, scope:ui, type:bug

#434 💄 (ui): added loaders
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
  frontend/apps/slip-snapper/src/app/components/SlipItems.tsx
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/apps/slip-snapper/src/app/tests/api/apiCall.test.js
  frontend/apps/slip-snapper/src/app/tests/pages/App.spec.tsx
  frontend/apps/slip-snapper/src/app/tests/pages/Home.spec.tsx
  frontend/apps/slip-snapper/src/app/tests/pages/__snapshots__/App.spec.tsx.snap
Labels: type:enhancement, priority:medium, scope:ui

#435 ✨ (feature/validation) Item validation
  backend/api/apps/src/routes/item.js
  backend/api/apps/tests/routes/items.test.js
Labels: type:enhancement, priority:high, scope:api, scope:feature

#436 🩹(bug): CSP improvement and removal of unused imports
  frontend/apps/slip-snapper/src/app/components/Menu.tsx
  frontend/apps/slip-snapper/src/app/components/ProfileImage.tsx
  frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
  frontend/apps/slip-snapper/src/app/components/SlipItems.tsx
  frontend/apps/slip-snapper/src/app/components/UserStats.tsx
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
  frontend/apps/slip-snapper/src/app/pages/ForgotPass.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
  frontend/apps/slip-snapper/src/index.html
  frontend/apps/slip-snapper/src/loadWorker.js
Labels: priority:low, scope:repository, type:bug

#437 🐛 (bug): Bug fixes to AddEntry page
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
Labels: priority:medium, scope:ui, type:bug

#438 🐛 (imageprocessing): change to image processing
  backend/api/apps/src/imageProcessor.js
  backend/api/apps/src/routes/auth.js
  frontend/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  frontend/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  frontend/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  frontend/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  frontend/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  frontend/apps/slip-snapper/src/app/components/ReportItem.tsx
  frontend/apps/slip-snapper/src/app/components/SlipItems.tsx
  frontend/apps/slip-snapper/src/app/components/usePhotoGallery.js
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: priority:high, type:bug, type:change, scope:feature

#439 🐛 (ui): Bug fixes in EditReceipt Page
  frontend/apps/slip-snapper/src/app/pages/AddEntry.tsx
  frontend/apps/slip-snapper/src/app/pages/EditReceipt.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
  frontend/apps/slip-snapper/src/app/tests/pages/__snapshots__/EditReceipt.test.tsx.snap
Labels: priority:medium, scope:ui, type:bug

#440 🐛 (bug): Various bug fixes
  backend/api/apps/src/routes/report.js
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/theme/addEntry.css
  frontend/apps/slip-snapper/src/app/theme/profile.css
Labels: priority:low, scope:ui, type:bug

#441 (Feature/categoriser): implemented text categoriser
  README.md
  backend/api/.gitignore
  backend/api/apps/itemCategoriser/categorizer.js
  backend/api/apps/itemCategoriser/dataSet_Generation/generator.js
  backend/api/apps/itemCategoriser/itemCategoriser.js
  backend/api/apps/itemCategoriser/itemcategory/weights.bin
  backend/api/apps/itemCategoriser/weights.json
  backend/api/apps/tests/parser.test.js
  backend/api/apps/textProcessor/text_parser/parser.js
Labels: priority:high, scope:api, type:change

#442 🐛 (register): fix for register token
  frontend/apps/slip-snapper-e2e/src/integration/home-integration.spec.ts
  frontend/apps/slip-snapper-e2e/src/integration/login-integration.spec.ts
  frontend/apps/slip-snapper-e2e/src/integration/navigation-integration.spec.ts
  frontend/apps/slip-snapper/src/app/components/Budget.tsx
  frontend/apps/slip-snapper/src/app/components/EditBudgets.tsx
  frontend/apps/slip-snapper/src/app/components/NavButtons.tsx
  frontend/apps/slip-snapper/src/app/pages/ForgotPass.tsx
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: priority:high, type:bug, type:change, type:test, scope:feature

#443 (Bugs/UpdatesReport): fixed bug generation
  backend/api/apps/src/routes/auth.js
  backend/api/apps/src/routes/report.js
  backend/api/apps/tests/routes/auth.test.js
Labels: priority:low, scope:api, type:bug

#444 (Feature/documentation) Updated readME
  README.md
Labels: type:documentation, priority:low, scope:repository
