Repository COS301-SE-2022/Slip-Snapper, pull requests merged in 2022-06, with the labels that each got.

#112 :lipstick: (ui): Updated Login Page UI
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/app/theme/LoginRegister.css
Labels: type:enhancement, priority:low, scope:ui

#114 ✨ (Feature/api): Added budget api calls and db connection basics
  backend/api/apps/src/db.js
  backend/api/apps/src/index.js
  backend/api/apps/src/routes/report.js
  backend/api/apps/tests/db.test.js
  backend/api/apps/tests/index.test.js
  backend/api/package.json
  backend/api/yarn.lock
Labels: priority:low, scope:db, scope:api, type:feature

#116 💄(ui): Updated the Register Page's UI
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
Labels: type:enhancement, priority:low, scope:ui

#117 💄(ui): Updated the CSS in register page
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/app/theme/login.css
  frontend/apps/slip-snapper/src/app/theme/register.css
Labels: type:enhancement, priority:low, scope:ui

#119 🎨 (Feature/api) moved unit tests, and expanded them
  backend/api/apps/server.js
  backend/api/apps/src/db.js
  backend/api/apps/src/index.js
  backend/api/apps/src/routes/auth.js
  backend/api/apps/src/routes/item.js
  backend/api/apps/src/routes/ocr.js
  backend/api/apps/src/routes/report.js
  backend/api/apps/src/users.json
  backend/api/apps/tests/auth.test.js
  backend/api/apps/tests/index.test.js
  backend/api/apps/tests/items.test.js
  backend/api/apps/tests/ocr.test.js
  backend/api/apps/tests/report.test.js
  backend/api/jsconfig.json
  backend/api/package.json
  backend/api/yarn.lock
Labels: type:enhancement, priority:low, scope:api, type:change, type:test

#121 ✅ (login): Wrote jest tests for login page
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/theme/login.css
  frontend/apps/slip-snapper/src/app/theme/register.css
Labels: type:enhancement, priority:low, scope:ui, type:test

#122 🎨 (Feature/api): refactored api calls for item
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/item.js
  backend/api/apps/tests/items.test.js
  backend/api/apps/tests/routes/auth.test.js
  backend/api/apps/tests/routes/items.test.js
  backend/api/apps/tests/routes/ocr.test.js
  backend/api/apps/tests/routes/report.test.js
Labels: type:enhancement, priority:low, scope:api

#120 ✅ (cicd): inclusion of backend in codecov
  .github/workflows/BackendCITest.yml
  .github/workflows/full.yml
Labels: priority:medium, scope:cicd, type:change

#123 ✅ (tests) : Added Jest testing for Login & Register pages
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
Labels: priority:medium, scope:ui, type:test

#124 🐛 (Bug/jest-fetch): Fix for jest fetch issue
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/components/FetchData.js
  frontend/apps/slip-snapper/src/app/components/NavButtons.tsx
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/hooks/OCR.tsx
  frontend/package.json
  frontend/yarn.lock
Labels: priority:low, scope:ui, type:bug

#126 💄 (ui): Added popups for the Logout and budget
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/pages/ViewReports.tsx
Labels: type:enhancement, priority:low, scope:ui

#127 ✨ (feature-parser): Added basic files for parser
  backend/api/apps/textProcessor/processor.js
  backend/api/apps/textProcessor/text_categoriser/categorizer.js
  backend/api/apps/textProcessor/text_parser/parser.js
Labels: type:enhancement, priority:low, type:feature, scope:feature

#129 :lipstick: (ui): Added Edit Slip page
  frontend/apps/slip-snapper/src/app/App.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
  frontend/apps/slip-snapper/src/assets/icon/temp_logo.png
  frontend/apps/slip-snapper/src/assets/mock-receipts/IMG_5593.jpg
  frontend/apps/slip-snapper/src/assets/mock-receipts/IMG_5594.jpg
Labels: priority:low, scope:ui, type:feature

#130 💄(ui): Added UI for the Edit Slips page
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
Labels: type:enhancement, priority:low, scope:ui

#132 :lipstick: (ui): Edited Edit Slip page UI
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
Labels: type:enhancement, priority:low, scope:ui

#133 :lipstick: (ui) Extraction of input
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
Labels: type:enhancement, priority:low, scope:ui

#134 🎨 (Feature/api): connected api calls to the database
  backend/api/.gitignore
  backend/api/apps/src/db.js
  backend/api/apps/src/items.json
  backend/api/apps/src/routes/auth.js
  backend/api/apps/src/routes/item.js
  backend/api/apps/src/routes/report.js
  backend/api/apps/tests/db.test.js
  backend/api/apps/tests/routes/auth.test.js
  backend/api/apps/tests/routes/items.test.js
  backend/api/apps/tests/routes/report.test.js
  backend/api/package.json
  backend/api/prisma/schema.prisma
  backend/api/yarn.lock
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/components/FetchData.js
Labels: type:enhancement, priority:low, scope:api, type:change, type:feature, type:test

#135 🎨 (feature-api) Budget api calls connected to db
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/report.js
  backend/api/apps/tests/db.test.js
  backend/api/apps/tests/routes/report.test.js
Labels: type:enhancement, priority:low, scope:api, type:change

#136 :sparkles: (feature/textparser): Basic total extraction
  backend/api/apps/textProcessor/text_parser/parser.js
Labels: priority:medium, type:feature, scope:feature

#137 :lipstick: (ui) Budget updates after user input
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
Labels: type:enhancement, priority:low, scope:ui

#138 :ok_hand: (feature/ocr): refactor OCR
  frontend/apps/slip-snapper/src/app/components/TakePictureButton.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/hooks/OCR.tsx
  frontend/apps/slip-snapper/src/hooks/usePhotoGallery.ts
Labels: priority:medium, type:change, scope:feature

#139 :ok_hand: (feature/textparser): total and date extraction with array
  backend/api/apps/textProcessor/text_parser/parser.js
Labels: priority:medium, type:change, scope:feature

#140 ✨ (pwa) create service woker and update the manifest.json
  frontend/apps/slip-snapper/src/assets/icon/maskable_icon.png
  frontend/apps/slip-snapper/src/assets/icon/maskable_icon_x128.png
  frontend/apps/slip-snapper/src/assets/icon/maskable_icon_x192.png
  frontend/apps/slip-snapper/src/assets/icon/maskable_icon_x384.png
  frontend/apps/slip-snapper/src/assets/icon/maskable_icon_x48.png
  frontend/apps/slip-snapper/src/assets/icon/maskable_icon_x72.png
  frontend/apps/slip-snapper/src/assets/icon/maskable_icon_x96.png
  frontend/apps/slip-snapper/src/index.html
  frontend/apps/slip-snapper/src/offline.html
  frontend/package.json
  frontend/yarn.lock
Labels: priority:high, type:feature, scope:feature

#141 ✨ (pwa) service worker and project.json path updated
  frontend/apps/slip-snapper/project.json
  frontend/apps/slip-snapper/src/manifest.json
  frontend/apps/slip-snapper/src/service-worker.js
Labels: priority:high, type:feature, scope:feature

#143 ✅ (tests) : Added rendering tests for the Edit Slips page
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/components/TakePictureButton.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
Labels: priority:low, scope:ui, type:test

#144 ✨ (db) schema update
  backend/database/prisma/prisma/migrations/20220607161005_new_schema/migration.sql
  backend/database/prisma/prisma/migrations/20220607163030_no_email/migration.sql
  backend/database/prisma/prisma/schema.prisma
Labels: priority:low, scope:db, type:feature

#145 🎨 (Feature/api): updated api to work with new db structure
  backend/api/apps/server.js
  backend/api/apps/src/db.js
  backend/api/apps/src/index.js
  backend/api/apps/src/routes/auth.js
  backend/api/apps/src/routes/item.js
  backend/api/apps/src/routes/ocr.js
  backend/api/apps/src/routes/report.js
  backend/api/apps/tests/index.test.js
  backend/api/apps/tests/routes/auth.test.js
  backend/api/apps/tests/routes/items.test.js
  backend/api/apps/tests/routes/ocr.test.js
  backend/api/apps/tests/routes/report.test.js
  backend/api/apps/textProcessor/text_categoriser/categorizer.js
  backend/api/apps/textProcessor/text_parser/parser.js
  backend/api/prisma/schema.prisma
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/components/FetchData.js
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/app/pages/Login.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/pages/Register.tsx
  frontend/apps/slip-snapper/src/app/theme/variables.css
Labels: priority:medium, scope:api, type:change

#146 :lipstick: (ui) Added a progress bar for budgets
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/theme/profile.css
Labels: type:enhancement, priority:low, scope:ui

#147 :sparkles: (feature/textparser): Basic item extraction
  backend/api/apps/textProcessor/text_parser/parser.js
Labels: priority:medium, type:feature, scope:feature

#149 ✨ (db) user statistics queries
  backend/database/prisma/index.ts
  backend/database/prisma/prisma/migrations/20220607172719_newmigration/migration.sql
  backend/database/prisma/prisma/schema.prisma
Labels: priority:low, scope:db, type:feature

#150 🎨 (Feature/api): connected api stats call to frontend and db
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/report.js
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
Labels: type:enhancement, priority:high, scope:api

#148 :ok_hand: (feature/textparser): Grouped slip content
  backend/api/apps/textProcessor/text_parser/parser.js
Labels: priority:medium, type:change, scope:feature

#152 :sparkles: (feature/takepic): Loading prompt during scan
  frontend/apps/slip-snapper/src/hooks/usePhotoGallery.js
  frontend/apps/slip-snapper/src/hooks/usePhotoGallery.ts
Labels: priority:medium, type:feature, scope:feature

#155 🐛 (testing): test for genreteReport onClick
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/Tests/Home.spec.tsx
  frontend/apps/slip-snapper/src/app/pages/Home.tsx
  frontend/apps/slip-snapper/src/hooks/usePhotoGallery.js
Labels: priority:medium, type:test, scope:feature

#156 :pencil: (repo): Updated README.md
  README.md
Labels: type:documentation, priority:low, scope:repository

#157 :lipstick: (ui): Updated toast CSS files
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/theme/loading.css
  frontend/apps/slip-snapper/src/app/theme/toasts.css
  frontend/apps/slip-snapper/src/hooks/usePhotoGallery.js
Labels: type:enhancement, priority:low, scope:ui

#158 🐛 (feature-api): updated db query
  backend/api/apps/src/db.js
Labels: priority:low, scope:api, type:bug

#159 🎨 (Feature/api): Updated categorizer to use databse first
  backend/api/apps/src/db.js
  backend/api/apps/textProcessor/text_categoriser/categorizer.js
  backend/api/apps/textProcessor/text_parser/parser.js
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
  frontend/apps/slip-snapper/src/hooks/usePhotoGallery.js
Labels: type:enhancement, priority:low, scope:api

#161 💄 (ui) : Updated editslip UI
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
Labels: type:enhancement, priority:low, scope:ui

#163 :lipstick: (ui): Added "new budget" button to Personal Budget section
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
  frontend/apps/slip-snapper/src/app/theme/profile.css
Labels: type:enhancement, priority:medium, priority:low, scope:ui

#165 ✅ (test): added Jest tests for the Profile Page
  frontend/apps/slip-snapper/src/app/Tests/App.spec.tsx
  frontend/apps/slip-snapper/src/app/pages/Profile.tsx
Labels: priority:low, scope:ui, type:test

#164 🎨 (Feature/api): Updated frontend to add the item to the database
  backend/api/apps/src/db.js
  backend/api/apps/src/routes/item.js
  backend/api/apps/src/routes/report.js
  backend/api/apps/tests/routes/items.test.js
  backend/api/apps/textProcessor/text_parser/parser.js
  frontend/apps/slip-snapper/src/api/apiCall.js
  frontend/apps/slip-snapper/src/app/pages/EditSlip.tsx
  frontend/apps/slip-snapper/src/hooks/usePhotoGallery.js
Labels: type:enhancement, priority:medium, scope:api

#167 (Doc/readMe) Added files for demo 2 to read me
  README.md
Labels: type:documentation, priority:high, scope:feature
